# Dashboards need to be specified here to be created on TestGrid
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: googleoss-compute-image-tools
- name: googleoss-gcp-guest
- name: googleoss-test-infra
- name: googleoss-esp-v2-presubmit
- name: googleoss-esp-v2-periodic
- name: googleoss-en-server

dashboard_groups:
  - name: googleoss
    dashboard_names:
    - googleoss-compute-image-tools
    - googleoss-gcp-guest
    - googleoss-test-infra
    - googleoss-esp-v2-presubmit
    - googleoss-esp-v2-periodic
    - googleoss-en-server
